theme: jekyll-theme-minimal
title: Octocat's homepage
description: My name is Benjamin Stanga. I went to St. Mary's High School in Berkeley, California. I like game development and Magic: the Gathering.
